name=TinySSD1306
version=1.0.0
author=asa-lab-bit
maintainer=asa-lab-bit
sentence=Ultra lightweight SSD1306 library for ATtiny202/402/404.
paragraph=RAM usage is approximately 16 bytes. Compatible with SoftI2C_VPORT and designed for small AVR devices.
category=Display
url=https://github.com/asa-lab-bit/TinySSD1306
architectures=megaavr
